version: '3'
services:

  proxy:
    image:
      nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8086:8086"
      - "8083:8083"
      - "9200:9200"
    volumes:
      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/etc/nginx/htpasswd:/etc/nginx/htpasswd:ro"
      - "/etc/vlab/certs:/etc/ssl:ro"

  grafana:
    image:
      grafana/grafana:7.5.1
    restart: unless-stopped
    volumes:
      - /var/lib/grafana:/var/lib/grafana
      - /etc/grafana/grafana.ini:/etc/grafana/grafana.ini:ro

  influxdb:
    image:
      influxdb:1.7-alpine
    restart: unless-stopped
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb
      - /etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    command: ["-config", "/etc/influxdb/influxdb.conf"]

  elasticsearch:
    image:
      elasticsearch:5.6-alpine
